// Node types: "person", "organization", "location"
const graphData = {
    nodes: [
        // CENTER
        {id:"epstein",label:"Jeffrey Epstein",type:"center",radius:32,
            agency:"CENTRAL NODE",role:"Financier · Sex Trafficker · Convicted",status:"CONVICTED",networth:"$577M (at death)",
            intelRole:"Convicted sex offender and suspected intelligence asset. Died in federal custody 2019.",
            epsteinLink:"Every connection here documented through visits, emails, payments, or court filings.",
            significance:"His network of the world's most powerful men remains only partially prosecuted.",
            desc:"Jeffrey Epstein was a financier and convicted sex offender who ran a multi-decade trafficking operation targeting young women and minors. He cultivated heads of state, royalty, billionaires, and celebrities — offering access and capital in exchange for participation in a network designed to generate compromising material and blackmail leverage.",
            evidence:"Convicted 2008 in Florida on a secret non-prosecution deal. Re-arrested July 2019 on federal sex trafficking charges. Found dead August 10, 2019 in MCC New York — ruled suicide, disputed by independent pathologist Dr. Michael Baden who found evidence consistent with homicidal strangulation. Properties contained hidden cameras in bedrooms. His contact book listed over 1,000 names.",
            link:"Epstein is the center. Every other node connects through documented visits, financial ties, court testimony, victim allegations, or his own emails. Maxwell is the only person convicted despite Giuffre and others naming dozens of men under oath."},

        // CONVICTED
        {id:"maxwell_g",label:"Ghislaine Maxwell",type:"convicted",radius:24,
            agency:"CO-CONSPIRATOR — CONVICTED 2021",role:"Socialite · Recruiter · Trafficker",status:"CONVICTED",networth:"$20M (pre-arrest)",
            intelRole:"Epstein's partner and primary recruiter. Daughter of confirmed Mossad asset Robert Maxwell.",
            epsteinLink:"Recruited and groomed victims for decades. Managed household, travel, and client access.",
            significance:"20-year sentence. Refuses to name other participants. Protecting someone.",
            desc:"Ghislaine Maxwell was Epstein's long-term companion, fixer, and primary recruiter. She managed his properties, recruited girls as young as 14, and according to multiple victims, participated directly in abuse. She entered Epstein's world in 1991 immediately after her father Robert Maxwell — a confirmed Mossad asset — died under disputed circumstances.",
            evidence:"Convicted December 2021 on five counts including sex trafficking of a minor. Sentenced June 2022 to 20 years. Multiple victims testified she directly participated in grooming and abuse. She has refused to cooperate with prosecutors in identifying other participants throughout her sentence.",
            link:"Her silence — maintained through a 20-year federal sentence — is the central unanswered question of the case. Legal analysts widely believe she is protecting specific individuals."},

        {id:"brunel",label:"Jean-Luc Brunel",type:"convicted",radius:16,
            agency:"MC2 MODEL MANAGEMENT",role:"Modeling Mogul · European Recruiter",status:"DIED BEFORE TRIAL",networth:"$50M (estimated)",
            intelRole:"French modeling impresario. Used his agencies as a direct European victim pipeline for Epstein.",
            epsteinLink:"Received $1M from Epstein to found MC2. Supplied girls from Eastern Europe and Brazil.",
            significance:"Found dead in Paris cell Feb 2022 — second key witness to die before testifying.",
            desc:"Jean-Luc Brunel ran MC2 Model Management, directly funded by a $1M wire from Epstein, and used his modeling industry access to recruit vulnerable young women into Epstein's network. Virginia Giuffre and multiple other victims named him as a direct participant in abuse.",
            evidence:"$1M transfer from Epstein to MC2 documented. Multiple victims named Brunel as a direct abuser. Arrested France December 2020 on rape of minors charges. Found dead in his Paris prison cell February 19, 2022 — ruled suicide.",
            link:"His death before trial — like Epstein's — eliminated testimony that would have named his client list. Two key witnesses eliminated. The pattern has never been investigated."},

        {id:"nader",label:"George Nader",type:"convicted",radius:15,
            agency:"TRUMP/UAE POLITICAL FIXER",role:"Political Operative · Convicted Pedophile",status:"CONVICTED",networth:"UNKNOWN",
            intelRole:"Back-channel between Trump transition and UAE. Twice-convicted on child abuse charges.",
            epsteinLink:"Operated in same world of wealthy political brokers using access as a shield.",
            significance:"Convicted 2020: 10 years for child pornography and child sex trafficking.",
            desc:"George Nader was a political operative who served as a key back-channel between the Trump transition team and the UAE, and a central figure in the Mueller investigation. He was simultaneously a twice-convicted pedophile.",
            evidence:"First convicted Czech Republic 1991 for sexual abuse of minors. Convicted again US 2020 on transporting child pornography and sex trafficking of a minor — sentenced to 10 years. Mueller investigation cooperating witness.",
            link:"Nader demonstrates Epstein was not an anomaly but part of a broader ecosystem in which extremely wealthy political operatives with child abuse histories operated with impunity for decades."},

        // SUSPICIOUS / NAMED IN FILES
        {id:"trump",label:"Donald Trump",type:"suspicious",radius:24,
            agency:"45TH & 47TH US PRESIDENT",role:"Businessman · President",status:"NAMED IN FILES",networth:"$5.4B",
            intelRole:"Decades-long social relationship with Epstein. Publicly praised him. Named in victim deposition.",
            epsteinLink:"Called Epstein 'terrific guy who likes beautiful women, many on the younger side.'",
            significance:"Giuffre named Trump in deposition. Epstein died under his DOJ. AG's father gave Epstein his first job.",
            desc:"Donald Trump had a documented social relationship with Epstein from the late 1980s through the early 2000s. Both men moved in the same New York and Palm Beach elite circles. The circumstances of Epstein's 2019 death — under Trump's DOJ, run by Bill Barr whose OSS-officer father gave Epstein his career start at Dalton School — have never been formally examined.",
            evidence:"1992 video shows Trump and Epstein at Mar-a-Lago with cheerleaders. Trump said in 2002: 'I've known Jeff for fifteen years. Terrific guy. It is even said that he likes beautiful women as much as I do, and many of them are on the younger side.' Virginia Giuffre's deposition named Trump. Epstein held a Mar-a-Lago membership. AG Bill Barr, whose father Donald Barr (OSS officer) gave Epstein his career start at Dalton, oversaw DOJ during Epstein's arrest and death.",
            link:"The highest-profile living name in the files. His praise of Epstein, Giuffre's deposition, and Epstein dying under his administration — run by the son of the man who launched Epstein's career — form a pattern no investigation has ever examined."},

        {id:"clinton",label:"Bill Clinton",type:"suspicious",radius:21,
            agency:"42ND US PRESIDENT",role:"Former President",status:"NAMED IN FILES",networth:"$120M",
            intelRole:"Flew on Epstein's plane 26 documented times, sometimes without Secret Service.",
            epsteinLink:"26 confirmed flights on the Lolita Express. Multiple visits to Epstein's Manhattan townhouse.",
            significance:"Giuffre filings allege Clinton was seen on Epstein's island. Clinton denies.",
            desc:"Bill Clinton flew on Epstein's Boeing 727 — dubbed the Lolita Express — 26 documented times, including international trips for Clinton Foundation work and at least one journey without his Secret Service detail, an extraordinary departure from protocol for a former president.",
            evidence:"26 confirmed flights in pilot David Rodgers' logs. Clinton's office acknowledged flights but denies knowledge of crimes. Virginia Giuffre's filings allege she was present when Clinton visited the island — Clinton categorically denies ever visiting Little St. James.",
            link:"A former US President flew 26 times on a convicted sex trafficker's plane — sometimes without security. What was exchanged for that access has never been examined."},

        {id:"andrew",label:"Prince Andrew",type:"suspicious",radius:20,
            agency:"DUKE OF YORK — UK ROYAL",role:"British Royal · Former Trade Envoy",status:"SETTLED SUIT",networth:"$35M",
            intelRole:"Long documented friendship with Maxwell and Epstein. Photographed with Giuffre aged 17.",
            epsteinLink:"Stayed at multiple Epstein properties. Photograph places him with 17-year-old Giuffre.",
            significance:"Settled Giuffre civil suit for ~£12M in 2022. Stripped of all royal duties.",
            desc:"Prince Andrew's relationship with Maxwell and Epstein was extensive and long-documented. A photograph showing Andrew with his arm around Virginia Giuffre — then 17, who alleges she was trafficked to him — became the defining image of royal involvement in the scandal.",
            evidence:"Photograph with Giuffre and Maxwell at Maxwell's London home 2001, when Giuffre was 17. Andrew denied authenticity, claimed he couldn't sweat, gave a catastrophic BBC Newsnight interview in 2019. Settled Giuffre's US civil suit February 2022 for a reported ~£12M without admitting liability. Stripped of military titles and patronages.",
            link:"Paying eight figures to avoid civil trial is the strongest implicit acknowledgment of legal exposure outside Maxwell's conviction. The settlement prevents Giuffre from testifying against him in any future proceeding."},

        {id:"musk",label:"Elon Musk",type:"suspicious",radius:19,
            agency:"TESLA / SPACEX / X / US DOGE",role:"Billionaire · Presidential Adviser",status:"NAMED IN FILES",networth:"$338B",
            intelRole:"His team requested an island invitation. He emailed Epstein on Christmas Day.",
            epsteinLink:"Assistant sought island access. Musk asked Epstein for academic introductions.",
            significance:"His claim of minimal contact is directly contradicted by multiple documented correspondence points.",
            desc:"Elon Musk appears in the released Epstein files in ways that reveal active pursuit of Epstein. His assistant contacted Epstein explicitly requesting an invitation to Little St. James island. Musk himself emailed Epstein on Christmas Day and separately sought an introduction through Epstein's network.",
            evidence:"Released DOJ files include an email from a Musk assistant explicitly requesting an invitation to Little St. James island. A Christmas Day email from Musk to Epstein is documented. Separate correspondence shows Musk asking Epstein to facilitate an academic introduction — directly contradicting Musk's public claim of a single incidental meeting.",
            link:"The richest person in the world, now a senior US government adviser, actively sought entry to Epstein's private island. The full scope has not been examined by any public body."},

        {id:"gates",label:"Bill Gates",type:"suspicious",radius:19,
            agency:"MICROSOFT / GATES FOUNDATION",role:"Billionaire Philanthropist",status:"NAMED IN FILES",networth:"$134B",
            intelRole:"Met Epstein multiple times post-conviction. Foundation staff maintained extensive contact.",
            epsteinLink:"Met Epstein at least 3 times after 2008. Considered letting Epstein manage a charitable fund.",
            significance:"Melinda warned him. Divorce cited Epstein. Foundation adviser named in Epstein's will.",
            desc:"Bill Gates maintained sustained documented contact with Epstein years after his 2008 sex offender conviction. The relationship extended to plans for Epstein to manage a Gates charitable fund, significant enough that Epstein named a Gates Foundation adviser as backup executor of his will without that person's knowledge.",
            evidence:"Multiple meetings at Epstein's Manhattan townhouse documented 2011-2013. Gates Foundation chief scientific adviser Boris Nikolic named without his consent as backup executor of Epstein's will. Melinda Gates explicitly warned her husband. The Epstein connection was cited in the Gates divorce proceedings.",
            link:"Gates met a convicted sex offender repeatedly, was warned by his wife, and considered giving Epstein control of a charitable fund. What Epstein offered or held over Gates has never been disclosed."},

        {id:"wexner",label:"Les Wexner",type:"suspicious",radius:20,
            agency:"L BRANDS / VICTORIA'S SECRET",role:"Billionaire Retailer · Mega Group",status:"NAMED IN FILES",networth:"$5.3B",
            intelRole:"The unexplained source of Epstein's entire empire. Gave him $1.4B control and a $77M townhouse.",
            epsteinLink:"Full power of attorney. $77M Manhattan townhouse transferred for $0.",
            significance:"Without Wexner there are no planes, no island, no network. Never criminally investigated.",
            desc:"Les Wexner gave Epstein complete power of attorney over his finances, control of approximately $1.4 billion in assets, and the Manhattan townhouse at 9 E. 71st Street that became the operational center of Epstein's network, transferred for $0.",
            evidence:"Power of attorney document dated 1991. $77M townhouse transferred for zero consideration. Wexner is a founding member of the Mega Group — billionaires with documented Israeli intelligence ties. Wexner Foundation gave Ehud Barak $2M in 2004. After Epstein's arrest Wexner claimed Epstein had 'misappropriated vast sums.'",
            link:"Without Wexner there is no Epstein empire. All of it traces back to one man who has never faced a criminal investigation."},

        {id:"staley",label:"Jes Staley",type:"suspicious",radius:19,
            agency:"JPMORGAN / BARCLAYS CEO",role:"Banker · Epstein's Primary Banker",status:"UNDER INVESTIGATION",networth:"$120M",
            intelRole:"Epstein's most documented banking relationship. Exchanged ~1,200 emails with Epstein.",
            epsteinLink:"Visited Epstein in prison post-conviction. Sent 'snow white' email referencing a victim.",
            significance:"Lost Barclays CEO job. JPMorgan paid $290M to Epstein victims. Most damning paper trail.",
            desc:"Jes Staley is the single most damning financial figure in the released Epstein files. He maintained ~1,200 documented emails with Epstein and visited him in prison after conviction. The 'snow white' email referencing one of Epstein's victims is the most explicit piece of non-Epstein correspondence in the entire file release.",
            evidence:"Approximately 1,200 emails exchanged with Epstein. Visited Epstein in prison post-conviction. 'Snow white' email references a young woman in terms prosecutors found deeply concerning. Resigned as Barclays CEO 2021. JPMorgan paid $290M settlement to Epstein victims 2023. UK FCA investigation ongoing.",
            link:"The snow white email and 1,200 documented exchanges make Staley the most documented non-convicted figure in the network. JPMorgan's $290M settlement is an institutional admission that the bank enabled Epstein's operation."},

        {id:"dubin",label:"Glenn Dubin",type:"suspicious",radius:17,
            agency:"HIGHBRIDGE CAPITAL MANAGEMENT",role:"Hedge Fund Billionaire",status:"NAMED IN SUIT",networth:"$2.9B",
            intelRole:"Hedge fund billionaire. Wife Eva Andersson was Epstein's ex-girlfriend.",
            epsteinLink:"Named by Virginia Giuffre under oath. Name appears extensively in unsealed documents.",
            significance:"One of the most specific names in Giuffre's sworn testimony. Never investigated.",
            desc:"Glenn Dubin is a hedge fund billionaire whose wife Eva Andersson-Dubin was previously Epstein's girlfriend. Dubin was named by Virginia Giuffre under sworn oath as part of her account of being trafficked.",
            evidence:"Named by Virginia Giuffre in sworn deposition testimony. Name appears extensively throughout unsealed Epstein court documents. Wife Eva Andersson-Dubin was Epstein's former girlfriend. The Dubins received gifts from Epstein. No criminal investigation has been opened.",
            link:"Named under oath by Giuffre. The combination of his wife's prior relationship with Epstein and his own appearance in victim testimony places him among the most specifically implicated uncharged figures."},

        {id:"mitchell",label:"George Mitchell",type:"suspicious",radius:17,
            agency:"US SENATE MAJORITY LEADER",role:"Former Senate Majority Leader · Nobel Laureate",status:"NAMED IN SUIT",networth:"$25M (at death)",
            intelRole:"One of the most powerful US senators in modern history. Nobel Peace Prize winner.",
            epsteinLink:"Named by Virginia Giuffre in a deposition as someone she was directed to have sex with.",
            significance:"Denied all allegations. Never investigated. His stature made scrutiny nearly impossible.",
            desc:"George Mitchell served as US Senate Majority Leader and chief architect of the Good Friday Agreement. He was named by Virginia Giuffre in a sworn deposition as someone she was directed to have sex with as part of Epstein's trafficking operation.",
            evidence:"Named by Virginia Giuffre in sworn deposition. Mitchell issued a categorical denial. His stature as former Senate Majority Leader meant his name received far less press attention. No criminal investigation was opened.",
            link:"His political stature — Senate Majority Leader, architect of the Northern Ireland peace process — appears to have functioned as a shield against scrutiny."},

        {id:"sultan_brunei",label:"Sultan of Brunei",type:"suspicious",radius:17,
            agency:"BRUNEI — ABSOLUTE MONARCH",role:"Hassanal Bolkiah · Absolute Monarch",status:"NAMED IN FILES",networth:"$30B",
            intelRole:"Absolute ruler of Brunei. Documented history of paying for trafficked women globally.",
            epsteinLink:"Appears in Epstein's network files. Epstein cultivated access to his circle.",
            significance:"He and brother Prince Jefri sued for sex trafficking women to Brunei including a former Miss USA.",
            desc:"Sultan Hassanal Bolkiah of Brunei has a documented history of allegations involving the trafficking of women. He and his brother Prince Jefri were named in multiple lawsuits alleging they trafficked women including American entertainers and beauty queens.",
            evidence:"Former Miss USA Shannon Marketic filed suit in 1997 alleging she was trafficked to Brunei. Multiple other women filed similar allegations. The Sultan implemented sharia law in 2019 including death by stoning for gay sex. He appears in Epstein's contact files.",
            link:"His documented history of allegedly paying for trafficked women combined with his Epstein network appearance places him among the powerful men who used sovereign wealth and immunity as a shield."},

        {id:"dershowitz",label:"Alan Dershowitz",type:"suspicious",radius:17,
            agency:"HARVARD LAW — EPSTEIN'S ATTORNEY",role:"Law Professor · Defense Attorney",status:"SETTLED SUIT",networth:"$25M",
            intelRole:"Epstein's personal attorney. Negotiated the 2008 immunity deal. Named under oath by Giuffre.",
            epsteinLink:"Virginia Giuffre named him as a man she was trafficked to as a minor.",
            significance:"Settled Giuffre's suit 2023. FBI memo names him as Mossad-CIA liaison node.",
            desc:"Alan Dershowitz was Epstein's personal attorney, the lead negotiator of the 2008 non-prosecution agreement that immunized all unnamed co-conspirators, and one of the men named by Virginia Giuffre in sworn filings as someone she was directed to have sex with while a minor.",
            evidence:"Led the 2007-2008 Epstein plea negotiations producing criminal immunity for all unnamed co-conspirators. Virginia Giuffre named him in a sworn affidavit. Settled defamation suits against Giuffre in 2023. FBI Los Angeles field office memo names Dershowitz as connecting Mossad, Epstein, and the DOJ.",
            link:"Epstein's lawyer, a named alleged participant under oath, and a possible intelligence liaison — three roles in one man who negotiated the deal that protected every unnamed person in Epstein's network."},

        {id:"black",label:"Leon Black",type:"suspicious",radius:16,
            agency:"APOLLO GLOBAL MANAGEMENT",role:"Private Equity Billionaire",status:"NAMED IN FILES",networth:"$12.4B",
            intelRole:"Paid Epstein $158M — the largest known payment from any individual to Epstein.",
            epsteinLink:"$158M paid 2012-2017, years after Epstein's 2008 sex offender conviction.",
            significance:"Resigned as Apollo CEO when payments became public. Never criminally investigated.",
            desc:"Leon Black paid Jeffrey Epstein $158 million in fees between 2012 and 2017 — by far the largest known payment to Epstein by any single person, coming years after his 2008 conviction.",
            evidence:"Apollo Global commissioned a law firm review confirming $158M in payments. Black claimed advice saved him hundreds of millions in taxes. Resigned as Apollo CEO April 2021. A civil lawsuit alleged a non-consensual sexual relationship with a woman connected to Epstein's network — settled. The $158M has never been criminally investigated.",
            link:"Paying a convicted sex offender $158M for advice has never been examined by a grand jury."},

        {id:"joi_ito",label:"Joi Ito",type:"suspicious",radius:16,
            agency:"MIT MEDIA LAB — DIRECTOR",role:"Tech Investor · MIT Media Lab Director",status:"UNDER INVESTIGATION",networth:"$25M",
            intelRole:"MIT Media Lab director who visited Epstein in prison and actively concealed Epstein donations.",
            epsteinLink:"Visited Epstein in prison post-conviction. Routed millions in Epstein donations through MIT covertly.",
            significance:"Resigned in disgrace 2019 when the concealment was exposed by the New Yorker.",
            desc:"Joi Ito was director of the MIT Media Lab. He visited Epstein in prison after his 2008 conviction, accepted millions in donations from Epstein for MIT, and actively worked to conceal Epstein's identity as the source — labeling them as anonymous donors to avoid scrutiny.",
            evidence:"Ronan Farrow's 2019 New Yorker investigation revealed Ito received approximately $7.5M from Epstein and actively concealed Epstein's identity. Internal emails showed Ito explicitly instructing staff to keep Epstein's name off records. Ito resigned as MIT Media Lab director September 2019.",
            link:"Ito did not merely accept Epstein money — he actively concealed it. The deliberate concealment of a convicted sex offender's funding of a major academic institution is a different category of conduct from passive acceptance."},

        {id:"summers",label:"Larry Summers",type:"suspicious",radius:16,
            agency:"HARVARD UNIVERSITY / US TREASURY",role:"Treasury Secretary · Harvard President",status:"NAMED IN FILES",networth:"$40M",
            intelRole:"Harvard president who accepted millions in Epstein donations post-conviction and met him repeatedly.",
            epsteinLink:"Accepted $6.5M+ Epstein donations for Harvard. Met with Epstein multiple times post-2008.",
            significance:"Harvard accepted $9M+ total from Epstein. Summers never adequately explained the relationship.",
            desc:"Larry Summers served as US Treasury Secretary and Harvard president. During his tenure Harvard accepted over $9 million in donations from Epstein — including after his 2008 conviction. Summers met with Epstein personally on multiple occasions post-conviction.",
            evidence:"Harvard accepted approximately $9.1M from Epstein including post-conviction. Multiple documented meetings between Summers and Epstein post-2008. Summers facilitated introductions for Epstein into Harvard's academic network.",
            link:"A Harvard president meeting repeatedly with a convicted sex offender and accepting millions in his donations represents an institutional failure that legitimized Epstein in academic circles."},

        {id:"hoffman",label:"Reid Hoffman",type:"suspicious",radius:15,
            agency:"LINKEDIN / GREYLOCK PARTNERS",role:"Billionaire Tech Investor",status:"NAMED IN FILES",networth:"$2.5B",
            intelRole:"LinkedIn founder. Met Epstein post-conviction. Introduced Joi Ito to Epstein.",
            epsteinLink:"Met Epstein after 2008 conviction. Said he was trying to help Epstein 'rehabilitate.'",
            significance:"Introduced Joi Ito to Epstein, creating the chain that led to the MIT Media Lab scandal.",
            desc:"Reid Hoffman met Jeffrey Epstein after his 2008 sex offender conviction and introduced others to him — most significantly Joi Ito, whose introduction led directly to the MIT Media Lab funding scandal.",
            evidence:"Documented meetings with Epstein post-2008. Introduced Joi Ito to Epstein — leading to MIT Media Lab's $7.5M in concealed Epstein donations. Hoffman acknowledged the meetings and expressed regret.",
            link:"Hoffman introduced Ito to Epstein, creating the chain that led to the MIT scandal. Introducing a convicted sex offender to the head of a prestigious research institution has consequences beyond a single meeting."},

        {id:"krauss",label:"Lawrence Krauss",type:"suspicious",radius:15,
            agency:"THEORETICAL PHYSICIST",role:"Physicist · Author",status:"NAMED IN FILES",networth:"$5M",
            intelRole:"Physicist who traveled with Epstein repeatedly post-conviction and publicly defended him.",
            epsteinLink:"Traveled with Epstein multiple times after 2008. Aggressively defended him publicly.",
            significance:"Multiple separate sexual misconduct allegations against Krauss himself from 2018.",
            desc:"Lawrence Krauss maintained a close personal relationship with Epstein after his 2008 conviction — traveling with him and publicly defending him in ways that went far beyond any concern for rehabilitation.",
            evidence:"Traveled with Epstein post-conviction documented in released files and BuzzFeed reporting. Gave public statements defending Epstein used in his PR rehabilitation campaign. In 2018 multiple women brought separate sexual misconduct allegations against Krauss — he resigned from Arizona State University.",
            link:"Krauss publicly defended a convicted sex offender while simultaneously facing his own sexual misconduct allegations. His defense was used as part of Epstein's rehabilitation campaign."},

        {id:"copperfield",label:"David Copperfield",type:"suspicious",radius:15,
            agency:"ENTERTAINER",role:"Illusionist · Entertainer",status:"NAMED IN FILES",networth:"$875M",
            intelRole:"Named by multiple Epstein victims as present at Epstein events and island visits.",
            epsteinLink:"Named by Virginia Roberts and other victims as present at Epstein gatherings.",
            significance:"Multiple victim accounts place him at Epstein events. Never investigated.",
            desc:"David Copperfield was named by multiple Epstein victims as a person present at Epstein's gatherings and events. Virginia Roberts (Giuffre) and others placed him in Epstein's social world with specificity beyond peripheral contact.",
            evidence:"Named by Virginia Roberts and additional victims in accounts of Epstein's social events. Appears in Epstein's contact files. Copperfield has denied any inappropriate conduct. No criminal investigation opened.",
            link:"Named by multiple victims — not just in contact files but in accounts of being present at Epstein events. The specificity of victim testimony distinguishes this from peripheral social contact."},

        {id:"dimon",label:"Jamie Dimon",type:"suspicious",radius:16,
            agency:"JPMORGAN CHASE — CEO",role:"JPMorgan CEO",status:"NAMED IN FILES",networth:"$2B",
            intelRole:"CEO of JPMorgan for the entirety of Epstein's banking relationship with the bank.",
            epsteinLink:"Bank paid $290M to Epstein victims. Internal emails show executives knew who Epstein was.",
            significance:"JPMorgan's internal emails implicate senior executives. Dimon has never been questioned under oath.",
            desc:"Jamie Dimon has been CEO of JPMorgan Chase since 2005 — the entirety of the period during which JPMorgan maintained Epstein as a client despite his conviction and internal emails showing executives knew exactly who Epstein was.",
            evidence:"JPMorgan paid $290M settlement to Epstein victims in 2023. Internal JPMorgan emails showed executives were aware of Epstein's sex offender status while continuing to maintain his accounts. Dimon has never been questioned under oath about what he knew and when.",
            link:"JPMorgan facilitated Epstein's financial activities for years after his conviction. The bank's $290M settlement is an institutional admission. What senior leadership knew has never been answered under oath."},

        {id:"blair",label:"Tony Blair",type:"suspicious",radius:15,
            agency:"FORMER UK PRIME MINISTER",role:"Former PM · Consultant",status:"NAMED IN FILES",networth:"$75M",
            intelRole:"Former UK Prime Minister. Named as a cultivated contact in Epstein's files.",
            epsteinLink:"Meetings with Epstein documented. Named in released files as a cultivated relationship.",
            significance:"His name in Epstein's files has received almost no press coverage in the UK.",
            desc:"Tony Blair, former UK Prime Minister, appears in the released Epstein files as a contact Epstein cultivated. Meetings between Blair and Epstein are documented.",
            evidence:"Named in released Epstein contact and correspondence files. Meetings with Epstein documented. Blair's consultancy has significant Middle East and Gulf state business overlapping with the geopolitical networks Epstein cultivated.",
            link:"Blair's appearance in Epstein's files has been treated as peripheral by UK media despite his status as a former Prime Minister."},

        {id:"mort_z",label:"Mort Zuckerman",type:"suspicious",radius:15,
            agency:"ATLANTIC MEDIA / NY DAILY NEWS",role:"Media Mogul · Real Estate Billionaire",status:"NAMED IN FILES",networth:"$3.2B",
            intelRole:"Media mogul and billionaire real estate developer. Named in Epstein's contact files.",
            epsteinLink:"Named in released Epstein files with documented correspondence.",
            significance:"Owner of major media properties — may explain why his name receives minimal coverage.",
            desc:"Mort Zuckerman was a billionaire real estate developer and media mogul who owned Atlantic Media and the New York Daily News. He appears in Epstein's released contact files with documented correspondence.",
            evidence:"Named in released Epstein contact and correspondence files. Epstein cultivated relationships across New York's real estate and media elite. Zuckerman's ownership of media properties has been noted by analysts as potentially relevant to the limited press coverage his name receives.",
            link:"Zuckerman's presence in Epstein's files has received almost no press coverage — a pattern noted by researchers who observe that Epstein's media-connected associates tend to receive less scrutiny than others."},

        {id:"pritzker",label:"Tom Pritzker",type:"suspicious",radius:15,
            agency:"HYATT HOTELS — CHAIRMAN",role:"Billionaire · Hyatt Chairman",status:"NAMED IN FILES",networth:"$3.6B",
            intelRole:"Hyatt Hotels chairman. Extensive documented correspondence with Epstein in released files.",
            epsteinLink:"Named in released files with specific documented correspondence with Epstein.",
            significance:"One of the most extensively documented billionaire contacts in the released files.",
            desc:"Tom Pritzker is the executive chairman of Hyatt Hotels Corporation and a member of the Pritzker family. He appears in the released Epstein files with extensive documented correspondence.",
            evidence:"Named in released Epstein contact and correspondence files with documented exchanges. Epstein cultivated relationships with the Pritzker family across multiple members. Pritzker has not been named in any victim testimony and has not been accused of any wrongdoing.",
            link:"Pritzker's extensive documented correspondence with Epstein places him among the billionaire contacts whose full relationship with Epstein has not been publicly examined."},

        {id:"burkle",label:"Ron Burkle",type:"suspicious",radius:15,
            agency:"YUCAIPA COMPANIES",role:"Supermarket Billionaire · Clinton Associate",status:"NAMED IN FILES",networth:"$2B",
            intelRole:"Supermarket and private equity billionaire. Clinton associate. Named in Epstein's contact files.",
            epsteinLink:"Named in contact files with documented correspondence. Close Clinton associate in same social orbit.",
            significance:"His Clinton ties and presence in Epstein's files place him at the intersection of two documented networks.",
            desc:"Ron Burkle is a supermarket and private equity billionaire who was a major Democratic donor and close associate of Bill Clinton. He appears in Epstein's contact files.",
            evidence:"Named in released Epstein contact files. Documented social overlap through Clinton's network. Burkle traveled on private jets with Clinton on multiple occasions independently documented. No victim has named Burkle in any allegation.",
            link:"Burkle sits at the intersection of the Clinton social network and Epstein's contact files. His relationship with both Clinton and his appearance in Epstein's files has not been publicly examined."},

        {id:"lutnick",label:"Howard Lutnick",type:"suspicious",radius:17,
            agency:"NEWMARK / US COMMERCE SECRETARY",role:"Real Estate Mogul · Trump Commerce Secretary",status:"NAMED IN FILES",networth:"$1.5B",
            intelRole:"Trump's Commerce Secretary. Visited Epstein's private island with his family in December 2012.",
            epsteinLink:"Emails confirm he accepted an invitation to Little St. James in Dec 2012 arriving by yacht with wife and children.",
            significance:"His prior public claims of cutting ties with Epstein 'decades ago' directly contradicted by the island visit emails.",
            desc:"Howard Lutnick is the former chairman of Newmark and currently serves as Donald Trump's Secretary of Commerce. Emails in the 2026 DOJ release show Lutnick and his wife accepted an invitation to visit Epstein's private island Little St. James in December 2012.",
            evidence:"2026 DOJ release emails show Lutnick and wife accepted invitation to Little St. James December 2012, planning to arrive by yacht with children. Additional 2011 correspondence shows drinks with Epstein and discussion of a nearby building project. Lutnick had previously claimed he cut ties with Epstein 'decades ago.'",
            link:"A sitting US Cabinet member whose public statements about cutting ties with Epstein 'decades ago' are directly contradicted by his own emails showing a 2012 family island visit."},

        {id:"branson",label:"Richard Branson",type:"suspicious",radius:16,
            agency:"VIRGIN GROUP",role:"Billionaire · Virgin Group Founder",status:"NAMED IN FILES",networth:"$3B",
            intelRole:"Invited Epstein to his own island saying 'bring your harem.' Advised using Gates to rehabilitate Epstein.",
            epsteinLink:"2013 email inviting Epstein to Necker Island: 'As long as you bring your harem!'",
            significance:"Post-conviction correspondence with explicit references to Epstein's 'harem' — the most casually damning email in the files.",
            desc:"Richard Branson exchanged numerous emails with Epstein in the released files. In a 2013 message he invited Epstein to his private Caribbean island Necker Island, telling him to 'bring your harem.' He also advised Epstein to rehabilitate his image by convincing Bill Gates to publicly vouch for him.",
            evidence:"2013 email from Branson to Epstein: 'Any time you're in the area would love to see you. As long as you bring your harem!' Separate 2013 email advising Epstein to get Gates to tell the public Epstein had been 'a brilliant adviser to him.'",
            link:"The 'harem' email is the most casually explicit acknowledgment in the files that a named associate was aware of — and amused by — Epstein's access to young women."},

        {id:"tisch",label:"Steven Tisch",type:"suspicious",radius:15,
            agency:"NY GIANTS / LOEWS CORPORATION",role:"NFL Co-Owner · Film Producer",status:"NAMED IN FILES",networth:"$1.6B",
            intelRole:"New York Giants co-owner, Oscar-winning producer. Named more than 400 times in the released files.",
            epsteinLink:"In a 2013 email about a woman Epstein described, Tisch asked: 'Pro or civilian?'",
            significance:"400+ file mentions. The 'Pro or civilian?' exchange is the most explicit transactional email.",
            desc:"Steven Tisch, co-owner of the New York Giants and Academy Award-winning producer, is mentioned more than 400 times in the 2026 DOJ release. In a 2013 email exchange, after Epstein described a woman in crude terms, Tisch replied asking whether she was a professional sex worker or not.",
            evidence:"Named 400+ times in the 2026 DOJ release. 2013 email exchange: Epstein described a woman in crude physical terms; Tisch replied 'Pro or civilian?' He acknowledged emailing Epstein about 'adult women' and stated he 'deeply regrets' associating with Epstein.",
            link:"Tisch's own acknowledgment of emailing Epstein about 'adult women,' combined with the 'Pro or civilian?' exchange, is among the most explicitly transactional correspondence in the entire file release."},

        {id:"wasserman",label:"Casey Wasserman",type:"suspicious",radius:15,
            agency:"LA 2028 OLYMPICS — PRESIDENT",role:"Sports Executive · LA 2028 Olympics Head",status:"NAMED IN FILES",networth:"$400M",
            intelRole:"President of the LA 2028 Olympics organizing committee.",
            epsteinLink:"2003 email to Maxwell: 'What do I have to do to see you in a tight leather outfit?'",
            significance:"Head of the 2028 Olympics with documented flirtatious correspondence with Maxwell.",
            desc:"Casey Wasserman is the president of the organizing committee for the 2028 Los Angeles Summer Olympics. The 2026 DOJ release revealed flirtatious email exchanges between Wasserman and Ghislaine Maxwell in 2003.",
            evidence:"2003 email from Wasserman to Maxwell: 'I think of you all the time. So, what do I have to do to see you in a tight leather outfit?' Maxwell also invited Wasserman to a dinner at Epstein's house.",
            link:"The head of the LA 2028 Olympics had documented flirtatious correspondence with Maxwell and was personally invited to Epstein's home by her."},

        {id:"barak",label:"Ehud Barak",type:"suspicious",radius:24,
            agency:"ISRAEL DEFENSE FORCES / PRIME MINISTER OF ISRAEL",role:"Former Prime Minister · Former Defense Minister · Former IDF Chief of Staff",status:"NAMED IN FILES · PHOTOGRAPHED · EXPOSED",networth:"$30M+",
            intelRole:"Ehud Barak is the most senior intelligence-connected figure with documented, repeated, personal contact with Jeffrey Epstein. As former Prime Minister, Defense Minister, and Chief of Staff of the IDF, Barak sat at the apex of Israel's military-intelligence establishment — including oversight of Mossad. His relationship with Epstein was not casual or incidental. Barak visited Epstein's Manhattan townhouse, his island, and his New Mexico ranch. He was photographed entering Epstein's Manhattan residence in January 2016 — shielding his face — alongside young women. Barak received $2.3 million from the Wexner Foundation (controlled by Epstein's only known client, Les Wexner) for unspecified 'research.' He also received approximately $5 million from Epstein directly through a fund managed by Epstein. Former Israeli intelligence officer Ari Ben-Menashe has publicly stated that both Epstein and Ghislaine Maxwell were Israeli intelligence assets, and that Robert Maxwell — Ghislaine's father and confirmed Mossad agent — recruited Epstein into the operation in the 1980s. Barak's deep ties to Israeli intelligence, combined with his extensive personal relationship with Epstein, make him the single most important link between the Epstein network and the Israeli state.",
            epsteinLink:"Barak maintained a close personal and financial relationship with Epstein spanning at least 15 years. He visited Epstein's properties repeatedly — Manhattan, the island, New Mexico. Barak was photographed by the Daily Mail entering Epstein's Manhattan townhouse in January 2016, appearing to shield his face while young women were also entering the building. Barak acknowledged the visits but denied any wrongdoing. He received $2.3 million from the Wexner Foundation for a 'research program' that has never been publicly documented. He received approximately $5 million from Epstein through a limited partnership. Barak invested in Carbyne911 — an Israeli emergency call-handling startup — with $1 million in funding routed through Epstein. Virginia Giuffre named Barak in her testimony. After Epstein's death, Barak continued to minimize the relationship while photographs and financial records contradicted his public statements.",
            desc:"Ehud Barak, born February 12, 1942, is the most decorated soldier in Israeli history and served as the 10th Prime Minister of Israel (1999-2001). He previously served as Chief of Staff of the IDF (1991-1995), head of Military Intelligence Directorate (Aman), and commanded Sayeret Matkal — Israel's most elite special forces unit. He later served as Defense Minister (2007-2013) under Netanyahu. After leaving politics, Barak entered private business and maintained a close relationship with Jeffrey Epstein that included frequent visits, financial transactions totaling millions of dollars, and business partnerships. The Daily Mail photographed Barak entering Epstein's Manhattan townhouse in January 2016, his face partially concealed, as young women were simultaneously entering the building. Barak's business ventures included Carbyne911, an Israeli surveillance technology startup that received funding routed through Epstein. The company's technology — emergency call geo-location — has obvious intelligence applications. Barak also partnered with Epstein through a company called Sum(x), receiving approximately $5 million. His relationship with Wexner — Epstein's only known client and alleged Mega Group member — included $2.3 million from the Wexner Foundation for a 'research program' that produced no publicly available research. Barak has acknowledged visiting Epstein's island and Manhattan residence multiple times but has denied any involvement in or knowledge of trafficking. His statements have been contradicted by photographs, financial records, flight logs, and victim testimony.",
            evidence:"Photographed by the Daily Mail entering Epstein's NYC townhouse (January 2016) while shielding his face, with young women entering simultaneously. Received $2.3M from Wexner Foundation for undocumented 'research.' Received approximately $5M from Epstein-linked investment fund. Co-invested with Epstein in Carbyne911, an Israeli surveillance-tech company. Virginia Giuffre named Barak in testimony. Flight logs place Barak on Epstein-connected travel. Visited Epstein's island, Manhattan townhouse, and New Mexico ranch — all confirmed by Barak himself in interviews. Continued visiting Epstein after 2008 conviction. As former PM and Defense Minister, had direct oversight of Mossad and Israeli intelligence. Barak's military intelligence background (head of Aman, commander of Sayeret Matkal) means he was trained in covert operations, intelligence tradecraft, and compartmentalized operations. His visits to a convicted sex offender cannot be explained as social naivety — he is one of the most operationally experienced intelligence figures in the world.",
            significance:"Barak is not a peripheral figure who attended a dinner party. He is the former Prime Minister and Defense Minister of Israel — the nation whose intelligence service is most frequently linked to the Epstein operation — and he maintained a deep, financial, personal, and business relationship with Epstein spanning over a decade. He received millions from both Epstein and Wexner. He was photographed visiting Epstein alongside young women. He partnered with Epstein in surveillance technology. And he is one of the most senior intelligence figures in Israeli history. Barak is the smoking gun connecting the Epstein network to state-level intelligence operations.",
            link:"The most decorated soldier in Israeli history, former Prime Minister, former Defense Minister, former head of Military Intelligence, received millions from Epstein and Wexner, was photographed entering Epstein's home with young women, partnered with Epstein on surveillance technology, and was named by a trafficking victim. If Epstein was an intelligence operation, Ehud Barak is where you find the handler."},

        {id:"thalberg",label:"Peter Thalberg",type:"suspicious",radius:17,
            agency:"US DEPARTMENT OF JUSTICE",role:"Former Deputy Attorney General",status:"NAMED IN FILES",networth:"$10M",
            intelRole:"Oversaw Epstein's 2008 plea deal as US Attorney for Southern Florida. Resigned in disgrace.",
            epsteinLink:"As Deputy Attorney General, he signed off on the 2008 non-prosecution agreement for Epstein.",
            desc:"Peter Thalberg was the US Attorney for the Southern District of Florida who oversaw Epstein's 2008 plea deal. He resigned in disgrace after the deal was made public.",
            evidence:"Signed the 2008 NPA. Resigned as Deputy Attorney General July 2019 after Epstein's re-arrest.",
            significance:"Thalberg's role in Epstein's plea deal and subsequent resignation make him a key figure in the cover-up of Epstein's activities.",
            link:"The prosecutor who oversaw Epstein's plea deal and resigned in disgrace."},

        {id:"putin",label:"Vladimir Putin",type:"possibly",radius:34,
            agency:"President of Russia",role:"President of the Russian Federation",status:"POSSIBLY INVOLVED",networth:"$200B+ (estimated)",
            intelRole:"Robert Maxwell was a confirmed KGB asset. The Maxwell-Mossad-KGB triangle places Russian intelligence within one degree of the Epstein operation.",
            epsteinLink:"No direct documented contact. However, the intelligence architecture surrounding Epstein — through Robert Maxwell's confirmed KGB ties — places Russian intelligence within the operational framework.",
            desc:"Former KGB officer who became President of Russia. Rose through the intelligence ranks during the same period Robert Maxwell was operating as a KGB asset. Has demonstrated a pattern of using kompromat as a primary tool of statecraft.",
            evidence:"Robert Maxwell's KGB ties documented by multiple intelligence historians. Putin's KGB career is public record. Russia's systematic use of kompromat is extensively documented.",
            significance:"If Epstein's operation was intelligence-linked, Russian intelligence would have been a consumer of the product. Maxwell's KGB ties provide the channel.",
            link:"Putin represents the geopolitical dimension of the Epstein case."},

        {id:"king_charles",label:"King Charles III",type:"possibly",radius:38,
            agency:"British Royal Family",role:"King of the United Kingdom",status:"POSSIBLY INVOLVED",networth:"$2B+",
            intelRole:"Brother of Prince Andrew. Close personal friendship with Jimmy Savile — confirmed serial predator protected by British intelligence.",
            epsteinLink:"Andrew is one of the most prominently named individuals. Charles's friendship with Savile demonstrates a pattern within the Royal Family of maintaining relationships with known predators.",
            desc:"King Charles III maintained a decades-long friendship with Jimmy Savile — posthumously revealed to have sexually abused over 500 people. Charles invited Savile to serve as unofficial adviser and hosted him at royal residences repeatedly.",
            evidence:"Charles-Savile friendship documented through royal correspondence released under FOI. Andrew named in Epstein victim testimony, settled for £12M.",
            significance:"The King maintained a close friendship with the most prolific pedophile in British history while his brother participated in the Epstein trafficking network.",
            link:"King Charles represents the apex of institutional protection."},

        {id:"mbs",label:"Mohammed bin Salman",type:"possibly",radius:32,
            agency:"Kingdom of Saudi Arabia",role:"Crown Prince of Saudi Arabia",status:"POSSIBLY INVOLVED",networth:"$2B+",
            intelRole:"Saudi intelligence has deep ties to the Epstein-adjacent network through Adnan Khashoggi and George Nader.",
            epsteinLink:"No direct documented contact. The Saudi intelligence pipeline runs through Khashoggi, Nader, and Gulf state intelligence.",
            desc:"Crown Prince and de facto ruler of Saudi Arabia. Ordered the murder of journalist Jamal Khashoggi per CIA assessment. Controls Saudi intelligence services.",
            evidence:"CIA assessed MBS ordered Khashoggi murder. George Nader — convicted pedophile — served as intermediary between Trump team and MBS.",
            significance:"MBS represents the Gulf state dimension of the Epstein network.",
            link:"The Saudi connection runs through decades of intelligence relationships."},

        {id:"kissinger",label:"Henry Kissinger",type:"possibly",radius:28,
            agency:"US State Department / NSC",role:"Former Secretary of State",status:"DECEASED (2023)",networth:"$50M (at death)",
            intelRole:"Listed in Epstein's black book. One of the most powerful intelligence-connected figures of the 20th century.",
            epsteinLink:"Named in Epstein's black book with direct contact details. Attended dinners where Epstein was present.",
            desc:"German-born American diplomat. National Security Advisor and Secretary of State under Nixon and Ford. Architect of modern American intelligence policy. Died 2023 at age 100.",
            evidence:"Listed in Epstein's black book (seized by FBI). Social overlap documented.",
            significance:"Kissinger's presence in Epstein's contact book places the father of modern American intelligence policy within one degree of a sexual blackmail operation.",
            link:"His connection to Epstein raises the question of whether the blackmail operation was connected to the intelligence architecture Kissinger helped build."},

        {id:"brennan",label:"John Brennan",type:"possibly",radius:24,
            agency:"Central Intelligence Agency",role:"Former CIA Director (2013-2017)",status:"POSSIBLY INVOLVED",
            intelRole:"CIA Director during a period when the intelligence community failed to act on Epstein's intelligence connections.",
            epsteinLink:"No direct contact documented. As CIA Director, would have had oversight of any intelligence equities connected to Epstein.",
            desc:"Career CIA officer. Director 2013-2017. Previously CIA station chief in Riyadh, connecting him to Saudi intelligence networks.",
            evidence:"CIA Directorship during Epstein investigation dormancy is public record. Acosta's 'belonged to intelligence' implies CIA involvement.",
            significance:"If Epstein was a CIA asset, the Director either authorized it, inherited it, or covered it up.",
            link:"Brennan represents the question: did the CIA Director know about Epstein?"},

        {id:"murdoch",label:"Rupert Murdoch",type:"possibly",radius:30,
            agency:"News Corp / Fox Corporation",role:"Media Mogul",status:"POSSIBLY INVOLVED",networth:"$20B",
            intelRole:"Controls the largest media empire in the English-speaking world. His outlets systematically underreported the Epstein story.",
            epsteinLink:"Listed in Epstein's black book. His media empire killed or buried Epstein stories. Maxwell-Murdoch overlap in British media documented.",
            desc:"Australian-born media mogul. Controls Fox News, NY Post, WSJ, The Sun, The Times. His media power gives him extraordinary influence over public narratives.",
            evidence:"Listed in Epstein's black book. Systematic underreporting by Murdoch outlets documented. Ex-wife Wendi Deng flagged by US counterintelligence.",
            significance:"Murdoch controls the mechanism by which Epstein's story was suppressed.",
            link:"Without media suppression, the Epstein story would have broken years earlier."},

        {id:"petraeus",label:"David Petraeus",type:"possibly",radius:22,
            agency:"CIA / US Army",role:"Former CIA Director, Four-Star General",status:"POSSIBLY INVOLVED",
            intelRole:"CIA Director 2011-2012. Already compromised by a honey trap scenario with biographer Paula Broadwell.",
            epsteinLink:"No direct contact documented. Demonstrated vulnerability to sexual compromise — the exact mechanism Epstein exploited.",
            desc:"Four-star general. CIA Director 2011-2012. Resigned after affair with biographer and sharing classified material. Pled guilty to mishandling classified information.",
            evidence:"Honey trap compromise documented through FBI investigation and guilty plea.",
            significance:"Petraeus proves the highest-ranking officials are vulnerable to sexual compromise.",
            link:"His case validates the operational concept behind Epstein's network."},

        {id:"comey",label:"James Comey",type:"possibly",radius:22,
            agency:"FBI",role:"Former FBI Director (2013-2017)",status:"POSSIBLY INVOLVED",
            intelRole:"FBI Director who did not reopen the Epstein investigation. His daughter Maurene Comey later prosecuted Maxwell.",
            epsteinLink:"FBI under Comey failed to pursue Epstein during a period when new evidence was available. FBI possessed Epstein's black book since 2009.",
            desc:"Former FBI Director fired by Trump in 2017. His daughter Maurene served on the team that convicted Maxwell.",
            evidence:"FBI possession of Epstein evidence during Comey tenure documented. FBI inaction 2013-2017 is public record.",
            significance:"The FBI Director's daughter prosecuting the case the FBI Director failed to pursue.",
            link:"Was the Bureau's failure incompetence, or the same intelligence protection Acosta described?"},

        {id:"starr",label:"Ken Starr",type:"possibly",radius:20,
            agency:"Epstein Legal Defense",role:"Former Solicitor General",status:"DECEASED (2022)",
            intelRole:"Hired by Epstein as defense attorney. Used political connections to help secure the lenient NPA.",
            epsteinLink:"Served on Epstein's defense team. Personally lobbied DOJ. Previously investigated Clinton yet defended Epstein whose network included Clinton.",
            desc:"Former Solicitor General and Clinton investigator. Later Baylor president (forced to resign over sexual assault scandal). Hired by Epstein for plea deal. Died 2022.",
            evidence:"Role on defense team documented in court filings. DOJ lobbying documented through FOIA. Baylor resignation over sexual assault mishandling.",
            significance:"The man who investigated Clinton over a consensual affair helped a child trafficker escape prosecution.",
            link:"Starr's involvement shows the legal protection extended to the most prestigious lawyers actively shielding Epstein."},

        {id:"boies",label:"David Boies",type:"possibly",radius:20,
            agency:"Boies Schiller Flexner LLP",role:"Attorney",status:"POSSIBLY INVOLVED",
            intelRole:"Represented both Epstein and Weinstein. Hired Israeli intelligence firm Black Cube to surveil Weinstein's victims.",
            epsteinLink:"Represented Epstein in civil cases. Also represented Giuffre — a conflict never formally sanctioned.",
            desc:"Founding partner of Boies Schiller Flexner. Famous for Bush v. Gore. Represented both Epstein and Weinstein, hiring ex-Mossad Black Cube against Weinstein accusers.",
            evidence:"Epstein representation in court filings. Black Cube hiring documented by Ronan Farrow. Conflict of interest documented.",
            significance:"Boies demonstrates how the legal system functions as a protection racket for wealthy predators.",
            link:"His hiring of former intelligence operatives to silence victims reveals the function of elite legal representation."},

        {id:"ellison",label:"Larry Ellison",type:"possibly",radius:24,
            agency:"Oracle Corporation",role:"Billionaire Tech Mogul",status:"POSSIBLY INVOLVED",networth:"$180B",
            intelRole:"Founder of Oracle, which has deep CIA and intelligence community ties. Epstein visited his private Hawaiian island.",
            epsteinLink:"Epstein visited Ellison's Hawaiian island Lanai. Both in overlapping tech-billionaire circles.",
            desc:"Oracle co-founder. Purchased 98% of Hawaiian island Lanai. Oracle has extensive CIA, NSA, and military intelligence contracts.",
            evidence:"Epstein visit to Lanai in travel records. Oracle intelligence contracts are public record.",
            significance:"Ellison represents the tech-intelligence nexus overlapping with the Epstein network.",
            link:"The Oracle-CIA relationship combined with the personal Epstein connection raises questions about the tech industry's intelligence ties."},

    ],

    links: [
        // Epstein center connections
        {source:"epstein", target:"maxwell_g", strength:1.0},
        {source:"epstein", target:"brunel", strength:0.8},
        {source:"epstein", target:"nader", strength:0.4},
        {source:"epstein", target:"trump", strength:0.7},
        {source:"epstein", target:"clinton", strength:0.8},
        {source:"epstein", target:"andrew", strength:0.7},
        {source:"epstein", target:"musk", strength:0.6},
        {source:"epstein", target:"gates", strength:0.7},
        {source:"epstein", target:"wexner", strength:0.9},
        {source:"epstein", target:"staley", strength:0.8},
        {source:"epstein", target:"dubin", strength:0.6},
        {source:"epstein", target:"mitchell", strength:0.5},
        {source:"epstein", target:"sultan_brunei", strength:0.4},
        {source:"epstein", target:"dershowitz", strength:0.8},
        {source:"epstein", target:"black", strength:0.7},
        {source:"epstein", target:"joi_ito", strength:0.6},
        {source:"epstein", target:"summers", strength:0.5},
        {source:"epstein", target:"hoffman", strength:0.5},
        {source:"epstein", target:"krauss", strength:0.5},
        {source:"epstein", target:"copperfield", strength:0.5},
        {source:"epstein", target:"dimon", strength:0.5},
        {source:"epstein", target:"blair", strength:0.4},
        {source:"epstein", target:"mort_z", strength:0.4},
        {source:"epstein", target:"pritzker", strength:0.5},
        {source:"epstein", target:"burkle", strength:0.4},
        {source:"epstein", target:"lutnick", strength:0.6},
        {source:"epstein", target:"branson", strength:0.6},
        {source:"epstein", target:"tisch", strength:0.6},
        {source:"epstein", target:"wasserman", strength:0.4},
        {source:"epstein", target:"barak", strength:0.7},
        {source:"epstein", target:"thiel", strength:0.6},
        {source:"epstein", target:"mandelson", strength:0.7},
        {source:"epstein", target:"barrack", strength:0.5},
        {source:"epstein", target:"casablancas", strength:0.5},
        {source:"epstein", target:"woody", strength:0.4},
        {source:"epstein", target:"spacey", strength:0.4},
        {source:"epstein", target:"tucker", strength:0.3},
        {source:"epstein", target:"richardson", strength:0.5},
        {source:"epstein", target:"sultan_ahmed", strength:0.3},
        {source:"epstein", target:"hawking", strength:0.4},
        {source:"epstein", target:"naomi", strength:0.3},
        {source:"epstein", target:"minsky", strength:0.4},
        {source:"epstein", target:"pinker", strength:0.3},
        {source:"epstein", target:"chomsky", strength:0.3},
        {source:"epstein", target:"deepak", strength:0.3},
        {source:"epstein", target:"nicholas_neg", strength:0.4},
        {source:"epstein", target:"lajcak", strength:0.3},
        {source:"epstein", target:"ferguson", strength:0.4},
        {source:"epstein", target:"brin", strength:0.4},
        {source:"epstein", target:"bannon", strength:0.5},
        {source:"epstein", target:"zuckerberg", strength:0.4},
        {source:"epstein", target:"mette_marit", strength:0.5},

        // Maxwell connections
        {source:"maxwell_g", target:"andrew", strength:0.7},
        {source:"maxwell_g", target:"brunel", strength:0.7},
        {source:"maxwell_g", target:"naomi", strength:0.5},
        {source:"maxwell_g", target:"woody", strength:0.4},
        {source:"maxwell_g", target:"wasserman", strength:0.4},
        {source:"maxwell_g", target:"brin", strength:0.4},
        {source:"maxwell_g", target:"casablancas", strength:0.5},
        {source:"maxwell_g", target:"minsky", strength:0.4},
        {source:"maxwell_g", target:"ferguson", strength:0.4},

        // Cross-connections
        {source:"clinton", target:"spacey", strength:0.4},
        {source:"clinton", target:"tucker", strength:0.4},
        {source:"clinton", target:"burkle", strength:0.5},
        {source:"wexner", target:"barak", strength:0.5},
        {source:"dershowitz", target:"pinker", strength:0.3},
        {source:"hoffman", target:"joi_ito", strength:0.5},
        {source:"hoffman", target:"zuckerberg", strength:0.4},
        {source:"hoffman", target:"musk", strength:0.3},
        {source:"joi_ito", target:"nicholas_neg", strength:0.5},
        {source:"joi_ito", target:"summers", strength:0.3},
        {source:"barak", target:"thiel", strength:0.5},
        {source:"barak", target:"barrack", strength:0.4},
        {source:"thiel", target:"zuckerberg", strength:0.3},
        {source:"thiel", target:"musk", strength:0.3},
        {source:"mandelson", target:"blair", strength:0.6},
        {source:"andrew", target:"ferguson", strength:0.5},
        {source:"brunel", target:"casablancas", strength:0.6},
        {source:"gates", target:"branson", strength:0.4},
        {source:"staley", target:"dimon", strength:0.5},
        {source:"trump", target:"lutnick", strength:0.4},
        {source:"trump", target:"bannon", strength:0.5},
        {source:"trump", target:"barrack", strength:0.5},
        {source:"trump", target:"nader", strength:0.3},
        {source:"musk", target:"brin", strength:0.3},

        // ─── INTELLIGENCE LINKS ───
        {source:"epstein", target:"robert_maxwell", strength:0.7},
        {source:"maxwell_g", target:"robert_maxwell", strength:1.0},
        {source:"epstein", target:"acosta", strength:0.7},
        {source:"epstein", target:"ben_menashe", strength:0.3},
        {source:"epstein", target:"barr_w", strength:0.5},
        {source:"epstein", target:"barr_d", strength:0.4},
        {source:"epstein", target:"hoffenberg", strength:0.6},
        {source:"epstein", target:"khashoggi", strength:0.4},
        {source:"epstein", target:"dougan", strength:0.2},
        {source:"barr_w", target:"barr_d", strength:0.9},
        {source:"barr_w", target:"trump", strength:0.5},
        {source:"barr_w", target:"acosta", strength:0.5},
        {source:"robert_maxwell", target:"ben_menashe", strength:0.6},
        {source:"robert_maxwell", target:"khashoggi", strength:0.5},
        {source:"acosta", target:"dershowitz", strength:0.5},

        // ─── POSSIBLY INVOLVED LINKS ───
        {source:"epstein", target:"putin", strength:0.3},
        {source:"putin", target:"robert_maxwell", strength:0.6},
        {source:"putin", target:"mbs", strength:0.4},
        {source:"epstein", target:"king_charles", strength:0.4},
        {source:"king_charles", target:"andrew", strength:1.0},
        {source:"king_charles", target:"ferguson", strength:0.7},
        {source:"epstein", target:"mbs", strength:0.3},
        {source:"mbs", target:"khashoggi", strength:0.7},
        {source:"mbs", target:"nader", strength:0.6},
        {source:"mbs", target:"sultan_brunei", strength:0.5},
        {source:"mbs", target:"trump", strength:0.6},
        {source:"epstein", target:"kissinger", strength:0.5},
        {source:"kissinger", target:"robert_maxwell", strength:0.4},
        {source:"kissinger", target:"khashoggi", strength:0.5},
        {source:"epstein", target:"brennan", strength:0.3},
        {source:"brennan", target:"barr_w", strength:0.4},
        {source:"brennan", target:"petraeus", strength:0.5},
        {source:"epstein", target:"murdoch", strength:0.5},
        {source:"murdoch", target:"robert_maxwell", strength:0.7},
        {source:"murdoch", target:"trump", strength:0.6},
        {source:"murdoch", target:"blair", strength:0.5},
        {source:"murdoch", target:"king_charles", strength:0.4},
        {source:"epstein", target:"petraeus", strength:0.3},
        {source:"epstein", target:"comey", strength:0.3},
        {source:"comey", target:"barr_w", strength:0.5},
        {source:"epstein", target:"starr", strength:0.7},
        {source:"starr", target:"dershowitz", strength:0.8},
        {source:"starr", target:"acosta", strength:0.6},
        {source:"starr", target:"clinton", strength:0.5},
        {source:"epstein", target:"boies", strength:0.6},
        {source:"boies", target:"dershowitz", strength:0.5},
        {source:"boies", target:"maxwell_g", strength:0.4},
        {source:"epstein", target:"ellison", strength:0.4},
        {source:"ellison", target:"gates", strength:0.4},
        {source:"ellison", target:"brin", strength:0.3},
        {source:"ellison", target:"thiel", strength:0.4},
    ]
};